---
title: "Run analysis"
author: "Adelaide Currin, Jennah Gosciak"
date: "2022-11-05"
output: html_document
---

```{r, setup}
library(tidyverse)
library(rlang)
library(fs)
library(tidycensus)
library(lehdr)
library(sf)
library(readxl)
library(plm)
library(lmtest)
library(sandwich)
library(wfe)
data_dir <- "C:/Users/Jennah/Desktop/Code/RMproject"

date <- Sys.Date() %>% 
  str_replace_all("-", "_")
```

```{r}
# define outcomes and covariates
outcomes <- c("C000rac", 
              "C000wac",
              "CE01rac", "CE01wac", "CE02rac", "CE02wac", "CE03rac", "CE03wac",
              "CR01rac", "CR01wac", "CR02rac", "CR02wac", "CRothrac", "CRothwac",
              "CT02rac", "CT02wac",
              "S000_same_tract", "S000_desig", "S000_elig")

log_outcomes <- str_c(outcomes, "_log")
cov <- c("log_median_household_income", "total_housing", "percent_white", "percent_postsec", "percent_rent", "percent_hc_covered", "percent_poverty", "percent_suplemental_income", "percent_employed")
```

```{r}
merged_oz <- readRDS("../2_output/analysis_file.RDS") %>% 
  mutate(CRothrac = rowSums(select(., c(CR03rac, CR04rac, CR05rac, CR07rac)), na.rm = T),
         CRothwac = rowSums(select(., c(CR03wac, CR04wac, CR05wac, CR07wac)), na.rm = T)) %>% 
  mutate(across(all_of(outcomes), ~if_else(is.na(.), 0, as.double(.)))) %>% 
  mutate(across(all_of(outcomes), .fns = list(log = ~log(if_else(. == 0, 1, as.double(.)))), .names = "{.col}_{.fn}")) %>% 
  mutate(post_treatment = post*treatment) %>% 
  mutate(percent_poverty = poverty / population) %>% 
  mutate(percent_white = white_population / population) %>% 
  mutate(percent_postsec = (associate + bachelor + professional_school + doctoral) / population) %>% 
  mutate(minutes_commute = (minutes_commute) / employed_population) %>% 
  mutate(percent_rent = (renter_occupied) / total_housing) %>% 
  mutate(percent_hc_covered = (native_born_hc_covered) / native_born) %>% 
  mutate(log_median_earnings = log(median_earnings)) %>% 
  mutate(log_median_household_income = log(median_household_income)) %>% 
  mutate(log_median_gross_rent = log(median_gross_rent)) %>% 
  mutate(percent_suplemental_income = supplemental_income / population) %>% 
  mutate(percent_employed = employed_population / population) %>% 
  filter(!is.na(GEOID) & !is.na(year)) %>% 
  filter((CONTIGUOUS == FALSE & DESIGNATED == FALSE) | DESIGNATED == TRUE) %>%
  mutate(C000rac_rate = if_else(population > 0, C000rac / population, 0)) %>% 
  mutate(year_fact2014 = if_else(year == 2014, 1, 0),
           year_fact2015 = if_else(year == 2015, 1, 0),
           year_fact2016 = if_else(year == 2016, 1, 0),
           year_fact2017 = if_else(year == 2017, 1, 0),
           year_fact2018 = if_else(year == 2018, 1, 0),
           year_fact2019 = if_else(year == 2019, 1, 0))

merged_oz

merged_oz %>% 
  group_by(year, DESIGNATED) %>% 
  summarize(n = n())
```


```{r}
# functions for each model
pooled_ols <- function(outcome, data, covariates) {
  return(lm(paste0(outcome, " ~ treatment:post + ",
  "treatment + post +", covariates),
               data = data))
}

trend_model <- function(outcome, data, covariates) {
  return(lm(paste0(outcome, " ~ treatment:year:post + treatment:post + treatment:year +",
  "treatment + year + post +", covariates),
               data = data))
  
}


twfe_model <- function(outcome, data, covariates) {
  return(plm(paste0(outcome, " ~ post_treatment"), 
               data = data, 
               index = c("GEOID", "year"), 
               model = "within", 
               effect = "twoways"))
  
}

twfe_model_covariates <- function(outcome, data, covariates) {
  covariates_list <- str_c(covariates, ":year_fact") %>% 
    str_c(collapse = " + ")
  return(plm(paste0(outcome, " ~ post_treatment + ", covariates_list), 
               data = data, 
               index = c("GEOID"), 
               model = "within", 
               effect = "individual"))
  
}

event_model <- function(outcome, data) {
  mod <- plm(paste0(outcome, " ~ treatment:year_fact2014 + treatment:year_fact2015 + ",
                    "treatment:year_fact2016 + treatment:year_fact2018 + treatment:year_fact2019 + ",
                    "year_fact2014 + year_fact2015 + year_fact2016 + year_fact2018 + year_fact2019"), 
               data = data, 
               index = c("GEOID"), 
               model = "within", 
               effect = "individual")
  
  return(mod)
}
```

```{r}
generate_model_output <- function(fit_model, outcome, treat_var, model_type, data, print) {
  sum_fit_plm <- summary(fit_model)

  if (model_type %in% c("twfe", "twfe_cov", "event")) {
    coef_names <- sum_fit_plm$coefficients %>% 
          row.names()
    
    coef_vals <- coeftest(fit_model,
                        vcovHC(fit_model, type = 'HC3', cluster = 'group'))
  } else {
    coef_names <- sum_fit_plm$coefficients[, 1] %>% 
      names()
    coef_vals <- coeftest(fit_model, vcov = vcovCL,
                                    type = "HC1",
                                    cluster = data$GEOID)
  }
  if (print == TRUE) {
    print(str_c("Running ", model_type, " model for ", outcome))
    coef_vals %>% 
      print()
  }
  
  coef_pos <- which(treat_var == coef_names)
  
  coef <- round(sum_fit_plm$coefficients[coef_pos, 1], 3)
  se <- round(coef_vals[coef_pos, 2], 3)
  pval <- round(coef_vals[coef_pos, 4], 4)
  coef_ast <- case_when(pval < 0.01 ~ paste0(coef, "***"),
                        pval < 0.05 ~ paste0(coef, "**"),
                        pval < 0.1 ~ paste0(coef, "*"))
  
  return(data.frame("outcome" = outcome,
               "treatment_post" = sum_fit_plm$coefficients[coef_pos, 1],
               "coef_asterisk" = coef_ast,
               "se" = se,
               "pval" = pval,
               "rsq" = round(sum_fit_plm$r.squared[[1]], 3),
               "model_type" = model_type))
}

run_model_outcome <- function(outcome, models, data=merged_oz, covariates=cov, print=TRUE) {
  covariates_orig <- covariates
  covariates <- str_c(covariates, collapse = " + ")
  results <- data.frame()
  if ("twfe" %in% models) {
    fit_plm <- twfe_model(outcome, data, covariates)
    results <- bind_rows(results, generate_model_output(fit_plm, outcome,
                                                        "post_treatment", "twfe", data, print=print)) 
  }
  if ("twfe_cov" %in% models) {
    fit_plm <- twfe_model_covariates(outcome, data, covariates_orig)
    results <- bind_rows(results, generate_model_output(fit_plm, outcome,
                                                        "post_treatment", "twfe_cov", data, print=print)) 
  }
  if ("did" %in% models) {
    fit_did <- pooled_ols(outcome, data, covariates)
    results <- bind_rows(results, generate_model_output(fit_did, outcome,
                                                        "treatment:post", "did", data, print=print)) 
  }
  if ("time_trend" %in% models) {
    fit_trend_lm <- trend_model(outcome, data, covariates)
    results <- bind_rows(results, generate_model_output(fit_trend_lm, outcome,
                                                        "treatment:year:post", "time_trend", data, print=print)) 
  }
  if ("event" %in% models) {
    fit_trend_lm <- event_model(outcome, data)
    results <- bind_rows(results, generate_model_output(fit_trend_lm, outcome,
                                                        "treatment:year_fact2019", "event", data, print=print)) 
  }
  return(results)
}

models <- c("did")
run_model_outcome("C000rac_log", models,  print=T)
```
```{r}
results <- map_dfr(log_outcomes, ~run_model_outcome(., models=models, print=FALSE))
results

# save to output
results %>%
  write_csv(str_glue("../2_output/results_{date}.csv"), na="")
```


```{r}
# placebo test
placebo_df <- merged_oz %>% 
  filter(post == 0) %>% 
  select(-c(post, post_treatment)) %>%
  mutate(post = if_else(year >= 2015, 1, 0),
         post_treatment = post*treatment)

placebo_results <- map_dfr(log_outcomes, ~run_model_outcome(., models=c("twfe_cov"), data = placebo_df,
                                                    print=FALSE))
placebo_results

# save to output
placebo_results %>% 
  write_csv(str_glue("../2_output/placebo_results_{date}.csv"), na="")
```

